//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSGVisitorManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlackListedVisitor
    {
        public int BlackListedVisitorID { get; set; }
        public long VisitorID { get; set; }
        public string MobileNo { get; set; }
        public bool IsBlackListed { get; set; }
        public string Reason { get; set; }
        public int EntryUserID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual CoreUser CoreUser { get; set; }
        public virtual CoreUser CoreUser1 { get; set; }
        public virtual Visitor Visitor { get; set; }
    }
}
