//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSGVisitorManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoVisitor
    {
        public long CoVisitorID { get; set; }
        public long VisitorID { get; set; }
        public string CoVisitorName { get; set; }
        public Nullable<int> IdentityTypeID { get; set; }
        public string IdentityNumber { get; set; }
        public string Gender { get; set; }
        public string VisitorAddress { get; set; }
        public int RelationshipID { get; set; }
        public int EntryUserID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual CoreIdentityType CoreIdentityType { get; set; }
        public virtual CoreRelationship CoreRelationship { get; set; }
        public virtual CoreUser CoreUser { get; set; }
        public virtual CoreUser CoreUser1 { get; set; }
        public virtual Visitor Visitor { get; set; }
    }
}
