//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSGVisitorManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NSGEmployee
    {
        public long NSGEmployeeID { get; set; }
        public string NSGEmployeeCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public Nullable<int> RankID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<int> QuarterTypeID { get; set; }
        public Nullable<int> QuarterNumber { get; set; }
        public bool IsActive { get; set; }
        public int EntryUserID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual CoreQuarterType CoreQuarterType { get; set; }
        public virtual CoreRank CoreRank { get; set; }
        public virtual CoreUnit CoreUnit { get; set; }
        public virtual CoreUser CoreUser { get; set; }
        public virtual CoreUser CoreUser1 { get; set; }
    }
}
